# nexus-menu — build and installation
#
#   make                              build the release binary
#   sudo make install                 install for everyone under /usr/local
#   make install PREFIX=$HOME/.local  install for the current user only
#   make install-launcher             launcher + icon only, no build
#   make install-completions          fish/bash/zsh completions only
#   make uninstall                    remove everything this installed
#
# Completion directories are overridable (FISHCOMPDIR, BASHCOMPDIR,
# ZSHCOMPDIR). The defaults are the system-wide vendor locations, which a
# per-user PREFIX does not put on the shell's search path: fish, for one,
# does not read ~/.local/share/fish/vendor_completions.d. For a user-local
# fish install use:
#   make install-completions FISHCOMPDIR=$$HOME/.config/fish/completions
#
# Packagers: DESTDIR is honoured throughout, and no cache-refresh commands
# run when it is set.

PREFIX  ?= /usr/local
DESTDIR ?=

BINDIR  ?= $(PREFIX)/bin
DATADIR ?= $(PREFIX)/share
APPDIR  ?= $(DATADIR)/applications
ICONDIR ?= $(DATADIR)/icons/hicolor/scalable/apps

FISHCOMPDIR ?= $(DATADIR)/fish/vendor_completions.d
BASHCOMPDIR ?= $(DATADIR)/bash-completion/completions
ZSHCOMPDIR  ?= $(DATADIR)/zsh/site-functions

CARGO ?= cargo
BIN   := target/release/nexus-menu

.PHONY: all build check validate install install-bin install-launcher \
        install-completions uninstall clean

all: build

build:
	$(CARGO) build --release --locked

check:
	$(CARGO) fmt --check
	$(CARGO) clippy --all-targets -- -D warnings
	$(CARGO) test

# desktop-file-validate exits 0 for warnings and hints, so treat any output
# at all as a failure — the same bar CI holds generated entries to.
validate:
	@out=$$(desktop-file-validate desktop/nexus-menu.desktop 2>&1 || true); \
	if [ -n "$$out" ]; then \
	  echo "desktop-file-validate reported problems:"; \
	  echo "$$out"; \
	  exit 1; \
	fi; \
	echo "desktop/nexus-menu.desktop is valid"

install: install-bin install-launcher install-completions

install-bin: build
	install -Dm755 $(BIN) $(DESTDIR)$(BINDIR)/nexus-menu

# The committed .desktop invokes `nexus-menu` by name, which only works if
# the binary is on the $PATH of the *desktop session* — which is not the same
# as a login shell's, and frequently lacks ~/.local/bin. The installed copy is
# therefore rewritten to the absolute path the binary lands at.
install-launcher:
	install -d $(DESTDIR)$(APPDIR)
	sed -e 's|sh -c "nexus-menu |sh -c "$(BINDIR)/nexus-menu |g' \
	    -e 's|^TryExec=nexus-menu$$|TryExec=$(BINDIR)/nexus-menu|' \
	    desktop/nexus-menu.desktop > $(DESTDIR)$(APPDIR)/nexus-menu.desktop
	chmod 644 $(DESTDIR)$(APPDIR)/nexus-menu.desktop
	install -Dm644 desktop/nexus-menu.svg $(DESTDIR)$(ICONDIR)/nexus-menu.svg
	@if [ -z "$(DESTDIR)" ]; then \
	  update-desktop-database "$(APPDIR)" 2>/dev/null || true; \
	  gtk-update-icon-cache -qtf "$(DATADIR)/icons/hicolor" 2>/dev/null || true; \
	fi

# Generated by the freshly built binary itself, so the scripts can never drift
# from the CLI they describe.
install-completions: build
	install -d $(DESTDIR)$(FISHCOMPDIR) $(DESTDIR)$(BASHCOMPDIR) $(DESTDIR)$(ZSHCOMPDIR)
	$(BIN) completions fish > $(DESTDIR)$(FISHCOMPDIR)/nexus-menu.fish
	$(BIN) completions bash > $(DESTDIR)$(BASHCOMPDIR)/nexus-menu
	$(BIN) completions zsh  > $(DESTDIR)$(ZSHCOMPDIR)/_nexus-menu
	chmod 644 $(DESTDIR)$(FISHCOMPDIR)/nexus-menu.fish \
	          $(DESTDIR)$(BASHCOMPDIR)/nexus-menu \
	          $(DESTDIR)$(ZSHCOMPDIR)/_nexus-menu

# Menu entries the tool generated are *not* removed here: they belong to the
# user, not to this install. Run `nexus-menu remove` first if you want
# them gone, because only the binary knows which files are its own.
uninstall:
	rm -f $(DESTDIR)$(BINDIR)/nexus-menu
	rm -f $(DESTDIR)$(APPDIR)/nexus-menu.desktop
	rm -f $(DESTDIR)$(ICONDIR)/nexus-menu.svg
	rm -f $(DESTDIR)$(FISHCOMPDIR)/nexus-menu.fish
	rm -f $(DESTDIR)$(BASHCOMPDIR)/nexus-menu
	rm -f $(DESTDIR)$(ZSHCOMPDIR)/_nexus-menu
	@if [ -z "$(DESTDIR)" ]; then \
	  update-desktop-database "$(APPDIR)" 2>/dev/null || true; \
	  gtk-update-icon-cache -qtf "$(DATADIR)/icons/hicolor" 2>/dev/null || true; \
	fi

clean:
	$(CARGO) clean
