//! kappfinder-rs — find installed applications that have no menu entry and
//! generate freedesktop `.desktop` files for them.
//!
//! A maintained, desktop-agnostic reimplementation of KDE's long-dead
//! KAppFinder. Like the original it is catalog-driven: it ships templates for
//! programs that commonly arrive without a menu entry, checks which of them
//! are actually installed, and offers to add only the ones missing.

mod catalog;
mod desktop;
mod prefixes;
mod registry;
mod scanner;
mod select;

use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

use anyhow::{Context, Result};
use clap::{CommandFactory, Parser, Subcommand};
use clap_complete::Shell;

use catalog::{AppTemplate, Catalog, Source};
use registry::Registry;

#[derive(Parser, Debug)]
#[command(
    name = "kappfinder-rs",
    version,
    about = "Find installed applications with no menu entry and create one",
    long_about = "kappfinder-rs scans $PATH for programs it has templates for, checks \
                  whether each already has a .desktop entry anywhere in the XDG \
                  application directories, and generates entries for the ones that do not.\n\n\
                  With no subcommand it performs a read-only scan and reports findings."
)]
struct Cli {
    /// Directory to write generated entries into
    /// [default: $XDG_DATA_HOME/applications]
    #[arg(long, value_name = "DIR", global = true)]
    dir: Option<PathBuf>,

    /// Extra catalog file to overlay on the built-in one
    /// [default: $XDG_CONFIG_HOME/kappfinder-rs/catalog.toml]
    #[arg(long, value_name = "FILE", global = true)]
    catalog: Option<PathBuf>,

    /// Treat NoDisplay/Hidden entries as missing, and offer to replace them
    #[arg(long, global = true)]
    ignore_nodisplay: bool,

    #[command(subcommand)]
    command: Option<Cmd>,
}

#[derive(Subcommand, Debug)]
enum Cmd {
    /// Report which catalog applications are installed but missing an entry
    Scan,

    /// Create entries for installed applications that are missing one
    Install {
        /// Accept every candidate without prompting
        #[arg(short, long)]
        yes: bool,
        /// Show what would be written, then stop
        #[arg(short = 'n', long)]
        dry_run: bool,
        /// Overwrite existing files in the target directory
        #[arg(long)]
        force: bool,
    },

    /// List every $PATH binary with no menu entry (heuristic, opt-in)
    Orphans {
        /// Do not filter out coreutils, libraries, and other obvious non-apps
        #[arg(long)]
        no_filter: bool,
        /// Show at most this many results (0 means no limit)
        #[arg(long, value_name = "N")]
        limit: Option<usize>,
    },

    /// Create an entry for specific binaries, catalogued or not
    Create {
        /// Binary names or absolute paths
        #[arg(value_name = "BIN", required = true)]
        bins: Vec<String>,
        /// Overwrite an existing file
        #[arg(long)]
        force: bool,
        /// Show what would be written, then stop
        #[arg(short = 'n', long)]
        dry_run: bool,
    },

    /// Delete entries previously generated by this tool
    Remove {
        /// Delete without prompting
        #[arg(short, long)]
        yes: bool,
        /// Show what would be deleted, then stop
        #[arg(short = 'n', long)]
        dry_run: bool,
    },

    /// Print the active catalog
    Catalog {
        /// Only show templates whose binary is not installed
        #[arg(long)]
        missing: bool,
    },

    /// Print a shell completion script to stdout
    Completions {
        /// Shell to generate completions for
        #[arg(value_enum)]
        shell: Shell,
    },

    /// Work with Windows applications in Wine prefixes and game launchers
    Wine {
        /// Extra prefix, or a directory to search for prefixes (repeatable)
        #[arg(long = "prefix", value_name = "DIR", global = true)]
        prefixes: Vec<PathBuf>,

        #[command(subcommand)]
        action: WineCmd,
    },
}

#[derive(Subcommand, Debug)]
enum WineCmd {
    /// List Wine prefixes: top-level hidden folders in your home directory,
    /// plus those Faugus, PortProton, Lutris and Heroic declare
    Prefixes,
}

/// A catalogued application that is installed but has no menu entry.
struct Candidate {
    template: AppTemplate,
    bin_path: PathBuf,
}

fn main() -> ExitCode {
    restore_default_sigpipe();

    let cli = Cli::parse();
    match run(cli) {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("error: {err:#}");
            ExitCode::FAILURE
        }
    }
}

/// Restore the default disposition of `SIGPIPE`.
///
/// The Rust runtime sets `SIGPIPE` to `SIG_IGN` before `main`, which turns a
/// closed downstream pipe into an `EPIPE` write error — and `println!` panics
/// on write errors. Without this, the perfectly ordinary
/// `kappfinder-rs orphans | head` aborts with a panic message instead of
/// exiting quietly. Dying on `SIGPIPE` is the correct behaviour for a CLI
/// that streams a long listing to stdout.
fn restore_default_sigpipe() {
    // SAFETY: called once at the very start of `main`, before any threads
    // exist. Installing SIG_DFL for SIGPIPE is async-signal-safe and is the
    // standard remedy used by Unix CLI tools written in Rust.
    unsafe {
        libc::signal(libc::SIGPIPE, libc::SIG_DFL);
    }
}

fn run(cli: Cli) -> Result<()> {
    let user_catalog = cli
        .catalog
        .clone()
        .unwrap_or_else(default_user_catalog_path);
    let target_dir = cli
        .dir
        .clone()
        .unwrap_or_else(registry::user_applications_dir);

    // Loaded on demand: `remove` and `completions` never read the catalog, so
    // a malformed user catalog must not stop them from working.
    let load_catalog = || Catalog::load(Some(&user_catalog));

    match cli.command.unwrap_or(Cmd::Scan) {
        Cmd::Scan => cmd_scan(&load_catalog()?, &target_dir, cli.ignore_nodisplay),
        Cmd::Install {
            yes,
            dry_run,
            force,
        } => cmd_install(
            &load_catalog()?,
            &target_dir,
            cli.ignore_nodisplay,
            yes,
            dry_run,
            force,
        ),
        Cmd::Orphans { no_filter, limit } => cmd_orphans(
            &load_catalog()?,
            &target_dir,
            cli.ignore_nodisplay,
            no_filter,
            limit,
        ),
        Cmd::Create {
            bins,
            force,
            dry_run,
        } => cmd_create(&load_catalog()?, &target_dir, &bins, force, dry_run),
        Cmd::Remove { yes, dry_run } => cmd_remove(&target_dir, yes, dry_run),
        Cmd::Catalog { missing } => cmd_catalog(&load_catalog()?, &user_catalog, missing),
        Cmd::Completions { shell } => cmd_completions(shell),
        Cmd::Wine { prefixes, action } => match action {
            WineCmd::Prefixes => cmd_wine_prefixes(&prefixes),
        },
    }
}

fn cmd_wine_prefixes(extra: &[PathBuf]) -> Result<()> {
    for path in extra {
        if !path.exists() {
            eprintln!("warning: --prefix {} does not exist", path.display());
        }
    }

    let home = prefixes::home();
    let env_prefix = env::var_os("WINEPREFIX")
        .map(PathBuf::from)
        .filter(|p| p.is_absolute());
    let drives = prefixes::drive_roots(&home);
    let found = prefixes::discover(&home, env_prefix.as_deref(), extra, &drives);

    let n = found.len();
    println!("{n} Wine prefix{} found\n", if n == 1 { "" } else { "es" });
    for prefix in &found {
        println!("  {:<10}  {}", prefix.owner.as_str(), prefix.path.display());
    }
    if n == 0 {
        println!("Nothing found. Name a location with `--prefix DIR` if yours is elsewhere.");
    }
    Ok(())
}

fn cmd_completions(shell: Shell) -> Result<()> {
    let mut cmd = Cli::command();
    let name = cmd.get_name().to_string();
    clap_complete::generate(shell, &mut cmd, name, &mut io::stdout());
    Ok(())
}

fn default_user_catalog_path() -> PathBuf {
    registry::config_home().join("kappfinder-rs/catalog.toml")
}

/// Collect catalogued applications that are installed but unreachable from
/// the menu.
fn find_candidates(catalog: &Catalog, registry: &Registry) -> (Vec<Candidate>, usize, usize) {
    let mut candidates = Vec::new();
    let mut installed = 0usize;
    let mut covered = 0usize;

    for template in catalog.apps.values() {
        let Some(bin_path) = scanner::lookup(&template.bin) else {
            continue;
        };
        installed += 1;
        if registry.covers(&template.bin).is_some() {
            covered += 1;
            continue;
        }
        candidates.push(Candidate {
            template: template.clone(),
            bin_path,
        });
    }

    candidates.sort_by(|a, b| a.template.bin.cmp(&b.template.bin));
    (candidates, installed, covered)
}

fn cmd_scan(catalog: &Catalog, target_dir: &Path, ignore_nodisplay: bool) -> Result<()> {
    let registry = Registry::build(Some(target_dir), ignore_nodisplay);
    let (candidates, installed, covered) = find_candidates(catalog, &registry);

    println!("kappfinder-rs — application menu entry finder\n");
    println!("  catalog templates     {}", catalog.len());
    println!("  installed on $PATH    {installed}");
    println!("  already in the menu   {covered}");
    println!("  missing an entry      {}", candidates.len());
    println!(
        "  desktop files seen    {} across {} director{}",
        registry.total_entries,
        registry.scanned_dirs.len(),
        if registry.scanned_dirs.len() == 1 {
            "y"
        } else {
            "ies"
        }
    );
    if !registry.generated.is_empty() {
        println!("  created by this tool  {}", registry.generated.len());
    }

    if candidates.is_empty() {
        println!("\nEvery catalogued application you have installed already has a menu entry.");
        return Ok(());
    }

    println!("\nInstalled but missing a menu entry:\n");
    print_candidates(&candidates);
    println!("\nRun `kappfinder-rs install` to create these entries.");
    Ok(())
}

fn print_candidates(candidates: &[Candidate]) {
    let width = candidates
        .iter()
        .map(|c| c.template.bin.len())
        .max()
        .unwrap_or(0)
        .max(4);

    for (i, c) in candidates.iter().enumerate() {
        let kind = if c.template.terminal {
            "terminal"
        } else {
            "gui"
        };
        println!(
            "  {:>3}  {:<width$}  {:<8}  {}",
            i + 1,
            c.template.bin,
            kind,
            c.template.name,
            width = width
        );
    }
}

fn cmd_install(
    catalog: &Catalog,
    target_dir: &Path,
    ignore_nodisplay: bool,
    yes: bool,
    dry_run: bool,
    force: bool,
) -> Result<()> {
    let registry = Registry::build(Some(target_dir), ignore_nodisplay);
    let (candidates, _, _) = find_candidates(catalog, &registry);

    if candidates.is_empty() {
        println!("Nothing to do: every catalogued application already has a menu entry.");
        return Ok(());
    }

    println!("Installed but missing a menu entry:\n");
    print_candidates(&candidates);
    println!("\nEntries will be written to {}", target_dir.display());

    // A dry run reports on everything; otherwise ask unless --yes was given.
    let chosen: Vec<usize> = if yes || dry_run {
        (0..candidates.len()).collect()
    } else {
        select::prompt_selection(candidates.len())?
    };

    if chosen.is_empty() {
        println!("Nothing selected.");
        return Ok(());
    }

    let mut created = 0usize;
    let mut skipped = 0usize;
    println!();
    for idx in chosen {
        let c = &candidates[idx];
        match write_entry(&c.template, &c.bin_path, target_dir, force, dry_run)? {
            Outcome::Created(path) => {
                println!("  created  {}", path.display());
                created += 1;
            }
            Outcome::Would(path) => {
                println!("  would create  {}", path.display());
            }
            Outcome::Exists(path) => {
                println!("  exists, skipped  {} (use --force)", path.display());
                skipped += 1;
            }
        }
    }

    if dry_run {
        println!("\nDry run: nothing was written.");
        return Ok(());
    }

    println!("\n{created} created, {skipped} skipped.");
    if created > 0 {
        refresh_desktop_database(target_dir);
    }
    Ok(())
}

fn cmd_orphans(
    catalog: &Catalog,
    target_dir: &Path,
    ignore_nodisplay: bool,
    no_filter: bool,
    limit: Option<usize>,
) -> Result<()> {
    let registry = Registry::build(Some(target_dir), ignore_nodisplay);
    let executables = scanner::all_executables();

    let mut orphans: Vec<(&String, &PathBuf)> = executables
        .iter()
        .filter(|(name, _)| registry.covers(name).is_none())
        // A catalogued program is a known application by definition, so the
        // heuristic filter never gets to hide one.
        .filter(|(name, _)| {
            no_filter || catalog.get(name.as_str()).is_some() || !scanner::looks_like_noise(name)
        })
        .collect();
    orphans.sort_by(|a, b| a.0.cmp(b.0));

    let total = orphans.len();
    // `--limit 0` reads as "no limit", not "show nothing".
    let shown = match limit {
        None | Some(0) => total,
        Some(n) => n.min(total),
    };

    println!(
        "{} of {} executables on $PATH have no menu entry{}.\n",
        total,
        executables.len(),
        if no_filter { "" } else { " (filtered)" }
    );

    let width = orphans
        .iter()
        .take(shown)
        .map(|(n, _)| n.len())
        .max()
        .unwrap_or(0)
        .max(4);

    for (name, path) in orphans.iter().take(shown) {
        println!("  {:<width$}  {}", name, path.display(), width = width);
    }

    if shown < total {
        println!("\n… {} more (raise or drop --limit).", total - shown);
    }
    println!(
        "\nThis list is heuristic. Create entries explicitly with:\n  kappfinder-rs create <BIN>…"
    );
    if !no_filter {
        println!("Pass --no-filter to see everything, including libraries and coreutils.");
    }
    Ok(())
}

fn cmd_create(
    catalog: &Catalog,
    target_dir: &Path,
    bins: &[String],
    force: bool,
    dry_run: bool,
) -> Result<()> {
    let mut created = 0usize;

    for raw in bins {
        let bin_path = scanner::lookup(raw)
            .with_context(|| format!("`{raw}` is not an executable on $PATH"))?;
        let key = desktop::basename(raw);

        let template = match catalog.get(&key) {
            Some(t) => t.clone(),
            None => {
                println!("note: `{key}` is not in the catalog; using generated defaults");
                AppTemplate::auto(&key)
            }
        };

        match write_entry(&template, &bin_path, target_dir, force, dry_run)? {
            Outcome::Created(path) => {
                println!("created  {}", path.display());
                created += 1;
            }
            Outcome::Would(path) => println!("would create  {}", path.display()),
            Outcome::Exists(path) => {
                println!("exists, skipped  {} (use --force)", path.display())
            }
        }
    }

    if !dry_run && created > 0 {
        refresh_desktop_database(target_dir);
    }
    Ok(())
}

fn cmd_remove(target_dir: &Path, yes: bool, dry_run: bool) -> Result<()> {
    let registry = Registry::build(Some(target_dir), false);

    // Only ever delete from writable locations we own.
    let user_dir = registry::user_applications_dir();
    let owned: Vec<&PathBuf> = registry
        .generated
        .iter()
        .filter(|p| p.starts_with(target_dir) || p.starts_with(&user_dir))
        .collect();

    if owned.is_empty() {
        println!("No entries generated by kappfinder-rs were found.");
        return Ok(());
    }

    println!("Entries generated by kappfinder-rs:\n");
    for path in &owned {
        println!("  {}", path.display());
    }

    if dry_run {
        println!("\nDry run: nothing was deleted.");
        return Ok(());
    }

    if !yes && !select::confirm(&format!("\nDelete these {} files?", owned.len()))? {
        println!("Cancelled.");
        return Ok(());
    }

    let mut removed = 0usize;
    for path in &owned {
        match fs::remove_file(path) {
            Ok(()) => {
                println!("removed  {}", path.display());
                removed += 1;
            }
            Err(e) => eprintln!("warning: could not remove {}: {e}", path.display()),
        }
    }

    println!("\n{removed} removed.");
    if removed > 0 {
        refresh_desktop_database(target_dir);
    }
    Ok(())
}

fn cmd_catalog(catalog: &Catalog, user_catalog_path: &Path, missing_only: bool) -> Result<()> {
    match &catalog.user_file {
        Some(p) => println!("Catalog: built-in + {}\n", p.display()),
        None => println!(
            "Catalog: built-in only (create {} to extend it)\n",
            user_catalog_path.display()
        ),
    }

    let width = catalog
        .apps
        .keys()
        .map(|k| k.len())
        .max()
        .unwrap_or(0)
        .max(4);

    let mut shown = 0usize;
    for (bin, app) in &catalog.apps {
        let installed = scanner::lookup(bin).is_some();
        if missing_only && installed {
            continue;
        }
        let mark = if installed { "installed" } else { "-" };
        let origin = match app.source {
            Source::User => " [user]",
            _ => "",
        };
        println!(
            "  {:<width$}  {:<9}  {}{}",
            bin,
            mark,
            app.name,
            origin,
            width = width
        );
        shown += 1;
    }

    println!("\n{shown} of {} templates shown.", catalog.len());
    Ok(())
}

enum Outcome {
    Created(PathBuf),
    Would(PathBuf),
    Exists(PathBuf),
}

/// Render and write one entry. Never overwrites unless `force`.
fn write_entry(
    template: &AppTemplate,
    bin_path: &Path,
    dir: &Path,
    force: bool,
    dry_run: bool,
) -> Result<Outcome> {
    let filename = format!("{}.desktop", sanitize_stem(&template.bin));
    let path = dir.join(filename);

    if path.exists() && !force {
        return Ok(Outcome::Exists(path));
    }
    if dry_run {
        return Ok(Outcome::Would(path));
    }

    fs::create_dir_all(dir)
        .with_context(|| format!("creating target directory {}", dir.display()))?;

    let contents = desktop::render(template, bin_path);

    // Write to a temporary file in the same directory, then rename, so a
    // crash can never leave a half-written entry in the menu.
    let tmp = path.with_extension("desktop.tmp");
    fs::write(&tmp, contents).with_context(|| format!("writing {}", tmp.display()))?;
    if let Err(err) = fs::rename(&tmp, &path) {
        // Do not leave the partial file lying around in an applications dir.
        let _ = fs::remove_file(&tmp);
        return Err(err).with_context(|| format!("installing {}", path.display()));
    }

    Ok(Outcome::Created(path))
}

/// Keep generated filenames to characters that are safe as a desktop file ID.
fn sanitize_stem(bin: &str) -> String {
    let cleaned: String = bin
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    if cleaned.is_empty() {
        "kappfinder-entry".to_string()
    } else {
        cleaned
    }
}

/// Ask the desktop environment to re-read the applications directory.
/// Entirely best-effort: most environments pick changes up via inotify.
fn refresh_desktop_database(dir: &Path) {
    match Command::new("update-desktop-database").arg(dir).status() {
        Ok(status) if status.success() => {
            println!("Refreshed the desktop database for {}", dir.display());
        }
        Ok(_) | Err(_) => {
            println!(
                "Note: `update-desktop-database` unavailable or failed; your desktop \
                 will normally pick up {} on its own.",
                dir.display()
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitizes_filenames() {
        assert_eq!(sanitize_stem("htop"), "htop");
        assert_eq!(sanitize_stem("my app"), "my-app");
        assert_eq!(sanitize_stem("a/b"), "a-b");
        assert_eq!(sanitize_stem(""), "kappfinder-entry");
    }

    #[test]
    fn cli_parses_without_subcommand() {
        let cli = Cli::try_parse_from(["kappfinder-rs"]).unwrap();
        assert!(cli.command.is_none());
    }

    #[test]
    fn cli_parses_install_flags() {
        let cli = Cli::try_parse_from(["kappfinder-rs", "install", "--yes", "-n"]).unwrap();
        match cli.command {
            Some(Cmd::Install { yes, dry_run, .. }) => {
                assert!(yes);
                assert!(dry_run);
            }
            other => panic!("unexpected command: {other:?}"),
        }
    }

    #[test]
    fn create_requires_at_least_one_binary() {
        assert!(Cli::try_parse_from(["kappfinder-rs", "create"]).is_err());
    }

    #[test]
    fn completions_require_a_known_shell() {
        assert!(Cli::try_parse_from(["kappfinder-rs", "completions"]).is_err());
        assert!(Cli::try_parse_from(["kappfinder-rs", "completions", "nonsense"]).is_err());
        for shell in ["fish", "bash", "zsh"] {
            assert!(Cli::try_parse_from(["kappfinder-rs", "completions", shell]).is_ok());
        }
    }

    #[test]
    fn generated_completions_mention_every_subcommand() {
        let mut cmd = Cli::command();
        let mut out = Vec::new();
        clap_complete::generate(Shell::Fish, &mut cmd, "kappfinder-rs", &mut out);
        let script = String::from_utf8(out).unwrap();
        for sub in [
            "scan",
            "install",
            "orphans",
            "create",
            "remove",
            "catalog",
            "completions",
        ] {
            assert!(script.contains(sub), "fish completions lack `{sub}`");
        }
    }

    #[test]
    fn wine_prefixes_parses_with_repeatable_prefix_flags() {
        let cli = Cli::try_parse_from([
            "kappfinder-rs",
            "wine",
            "prefixes",
            "--prefix",
            "/a",
            "--prefix",
            "/b",
        ])
        .unwrap();
        match cli.command {
            Some(Cmd::Wine { prefixes, action }) => {
                assert_eq!(prefixes, vec![PathBuf::from("/a"), PathBuf::from("/b")]);
                assert!(matches!(action, WineCmd::Prefixes));
            }
            other => panic!("unexpected command: {other:?}"),
        }
    }

    #[test]
    fn prefix_flag_works_before_the_wine_action() {
        let cli =
            Cli::try_parse_from(["kappfinder-rs", "wine", "--prefix", "/a", "prefixes"]).unwrap();
        assert!(matches!(cli.command, Some(Cmd::Wine { .. })));
    }

    #[test]
    fn wine_requires_an_action() {
        assert!(Cli::try_parse_from(["kappfinder-rs", "wine"]).is_err());
    }

    #[test]
    fn global_flags_work_after_subcommand() {
        let cli = Cli::try_parse_from(["kappfinder-rs", "install", "--dir", "/tmp/apps"]).unwrap();
        assert_eq!(cli.dir, Some(PathBuf::from("/tmp/apps")));
    }
}
