use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use walkdir::WalkDir;

use crate::prefixes::{self, Owner};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WineApp {
    pub prefix: PathBuf,
    pub owner: Owner,
    pub name: String,
    pub file: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WineLauncher {
    pub prefix: PathBuf,
    pub owner: Owner,
    pub name: String,
    pub target: PathBuf,
}

pub fn discover(prefixes: &[prefixes::Prefix]) -> Vec<WineApp> {
    let mut found = Vec::new();
    let mut seen = HashSet::new();

    for prefix in prefixes {
        let root = prefix.path.join("drive_c");
        if !root.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root)
            .follow_links(false)
            .max_depth(8)
            .into_iter()
            .filter_map(Result::ok)
        {
            let path = entry.path();
            if !path.is_file() {
                continue;
            }
            if !is_candidate(path) {
                continue;
            }
            let key = path.to_string_lossy().to_string();
            if seen.contains(&key) {
                continue;
            }
            seen.insert(key.clone());
            let label = display_name(path);
            found.push(WineApp {
                prefix: prefix.path.clone(),
                owner: prefix.owner,
                name: label,
                file: path.to_path_buf(),
            });
        }
    }

    found.sort_by(|a, b| a.name.cmp(&b.name));
    found
}

fn is_candidate(path: &Path) -> bool {
    let Some(ext) = path.extension().and_then(|e| e.to_str()) else {
        return false;
    };
    let ext = ext.to_ascii_lowercase();
    if !matches!(ext.as_str(), "exe" | "bat" | "cmd") {
        return false;
    }

    let lower = path
        .components()
        .filter_map(|c| c.as_os_str().to_str())
        .map(|s| s.to_ascii_lowercase())
        .collect::<Vec<_>>();

    lower.iter().all(|s| {
        !matches!(
            s.as_str(),
            "windows"
                | "winsxs"
                | "system32"
                | "syswow64"
                | "programdata"
                | "appdata"
                | "installer"
                | "temp"
                | "tmp"
                | "cache"
                | "drivers"
                | "mono"
                | "dotnet"
        )
    })
}

fn display_name(path: &Path) -> String {
    path.file_stem()
        .and_then(|s| s.to_str())
        .map(str::to_string)
        .unwrap_or_else(|| path.file_name().and_then(|s| s.to_str()).unwrap_or("Wine App").to_string())
}

pub fn render_desktop(app: &WineApp) -> String {
    let prefix = app.prefix.display();
    let unix_target = app.file.display();
    let exec = format!(
        "env WINEPREFIX=\"{}\" wine start /unix \"{}\"",
        prefix,
        unix_target
    );
    let filename = sanitize_file_name(&app.name);

    let mut out = String::new();
    out.push_str("# Generated by nexus-menu for a Wine application.\n");
    out.push_str("# Edit freely; `nexus-menu remove` removes files tagged with X-NexusMenu-Generated.\n");
    out.push_str("[Desktop Entry]\n");
    out.push_str("Type=Application\n");
    out.push_str("Version=1.0\n");
    out.push_str(&format!("Name={}\n", escape_value(&app.name)));
    out.push_str(&format!("Comment={}\n", escape_value("Launch from Wine prefix")));
    out.push_str(&format!("Exec={}\n", escape_value(&exec)));
    out.push_str("Terminal=false\n");
    out.push_str("Categories=Game;Utility;\n");
    out.push_str("StartupNotify=true\n");
    out.push_str("X-NexusMenu-Generated=true\n");
    out.push_str("X-NexusMenu-Source=wine\n");
    out.push_str(&format!("X-NexusMenu-Prefix={}\n", escape_value(&prefix)));
    out.push_str(&format!("X-NexusMenu-Target={}\n", escape_value(&unix_target)));
    out.push_str(&format!("X-NexusMenu-File={}\n", escape_value(&filename)));

    out
}

fn escape_value(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out
}

fn sanitize_file_name(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    if cleaned.is_empty() {
        "wine-app".to_string()
    } else {
        cleaned
    }
}

pub fn write_desktop(app: &WineApp, dir: &Path, force: bool, dry_run: bool) -> Result<Option<PathBuf>, std::io::Error> {
    let filename = format!("{}.desktop", sanitize_file_name(&app.name));
    let path = dir.join(filename);

    if path.exists() && !force {
        return Ok(None);
    }
    if dry_run {
        return Ok(Some(path));
    }

    fs::create_dir_all(dir)?;
    let tmp = path.with_extension("desktop.tmp");
    fs::write(&tmp, render_desktop(app))?;
    fs::rename(&tmp, &path)?;
    Ok(Some(path))
}

pub fn cmd_to_string(app: &WineApp) -> String {
    format!(
        "env WINEPREFIX=\"{}\" wine start /unix \"{}\"",
        app.prefix.display(),
        app.file.display()
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn windows_candidates_are_exe_or_batch_files() {
        let p = PathBuf::from("/tmp/drive_c/Program Files/Game/app.exe");
        assert!(is_candidate(&p));
        assert!(!is_candidate(&PathBuf::from("/tmp/drive_c/Windows/System32/cmd.exe")));
        assert!(is_candidate(&PathBuf::from("/tmp/drive_c/Program Files/Game/start.cmd")));
    }

    #[test]
    fn desktop_contents_include_generated_marker() {
        let app = WineApp {
            prefix: PathBuf::from("/tmp/prefix"),
            owner: Owner::Wine,
            name: "My Game".to_string(),
            file: PathBuf::from("/tmp/prefix/drive_c/Program Files/My Game/game.exe"),
        };
        let rendered = render_desktop(&app);
        assert!(rendered.contains("X-NexusMenu-Generated=true"));
        assert!(rendered.contains("Name=My Game"));
    }
}
}

